// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	Message
	Request
	Response
	Contact
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message_Type int32

const (
	Message_REQUEST  Message_Type = 0
	Message_RESPONSE Message_Type = 1
)

var Message_Type_name = map[int32]string{
	0: "REQUEST",
	1: "RESPONSE",
}
var Message_Type_value = map[string]int32{
	"REQUEST":  0,
	"RESPONSE": 1,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}
func (Message_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Request_Type int32

const (
	Request_PING     Request_Type = 0
	Request_FINDNODE Request_Type = 1
	Request_FINDDATA Request_Type = 2
	Request_STORE    Request_Type = 3
)

var Request_Type_name = map[int32]string{
	0: "PING",
	1: "FINDNODE",
	2: "FINDDATA",
	3: "STORE",
}
var Request_Type_value = map[string]int32{
	"PING":     0,
	"FINDNODE": 1,
	"FINDDATA": 2,
	"STORE":    3,
}

func (x Request_Type) String() string {
	return proto.EnumName(Request_Type_name, int32(x))
}
func (Request_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Response_Type int32

const (
	Response_PING           Response_Type = 0
	Response_FINDNODE       Response_Type = 1
	Response_FINDDATA_FOUND Response_Type = 2
	Response_FINDDATA_NODES Response_Type = 3
	Response_STORE          Response_Type = 4
)

var Response_Type_name = map[int32]string{
	0: "PING",
	1: "FINDNODE",
	2: "FINDDATA_FOUND",
	3: "FINDDATA_NODES",
	4: "STORE",
}
var Response_Type_value = map[string]int32{
	"PING":           0,
	"FINDNODE":       1,
	"FINDDATA_FOUND": 2,
	"FINDDATA_NODES": 3,
	"STORE":          4,
}

func (x Response_Type) String() string {
	return proto.EnumName(Response_Type_name, int32(x))
}
func (Response_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type Message struct {
	Type     Message_Type `protobuf:"varint,1,opt,name=type,enum=messages.Message_Type" json:"type,omitempty"`
	Sender   *Contact     `protobuf:"bytes,2,opt,name=sender" json:"sender,omitempty"`
	Request  *Request     `protobuf:"bytes,3,opt,name=Request" json:"Request,omitempty"`
	Response *Response    `protobuf:"bytes,4,opt,name=Response" json:"Response,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetType() Message_Type {
	if m != nil {
		return m.Type
	}
	return Message_REQUEST
}

func (m *Message) GetSender() *Contact {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Message) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Message) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

type Request struct {
	MessageID int64        `protobuf:"varint,1,opt,name=messageID" json:"messageID,omitempty"`
	Type      Request_Type `protobuf:"varint,2,opt,name=type,enum=messages.Request_Type" json:"type,omitempty"`
	ID        string       `protobuf:"bytes,3,opt,name=ID" json:"ID,omitempty"`
	Data      []byte       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Request) GetMessageID() int64 {
	if m != nil {
		return m.MessageID
	}
	return 0
}

func (m *Request) GetType() Request_Type {
	if m != nil {
		return m.Type
	}
	return Request_PING
}

func (m *Request) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Request) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Response struct {
	MessageID int64         `protobuf:"varint,1,opt,name=messageID" json:"messageID,omitempty"`
	Type      Response_Type `protobuf:"varint,2,opt,name=type,enum=messages.Response_Type" json:"type,omitempty"`
	Contacts  []*Contact    `protobuf:"bytes,3,rep,name=contacts" json:"contacts,omitempty"`
	Data      []byte        `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetMessageID() int64 {
	if m != nil {
		return m.MessageID
	}
	return 0
}

func (m *Response) GetType() Response_Type {
	if m != nil {
		return m.Type
	}
	return Response_PING
}

func (m *Response) GetContacts() []*Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Contact struct {
	ID       string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Address  string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	Distance string `protobuf:"bytes,3,opt,name=distance" json:"distance,omitempty"`
}

func (m *Contact) Reset()                    { *m = Contact{} }
func (m *Contact) String() string            { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()               {}
func (*Contact) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Contact) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Contact) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Contact) GetDistance() string {
	if m != nil {
		return m.Distance
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "messages.message")
	proto.RegisterType((*Request)(nil), "messages.request")
	proto.RegisterType((*Response)(nil), "messages.response")
	proto.RegisterType((*Contact)(nil), "messages.contact")
	proto.RegisterEnum("messages.Message_Type", Message_Type_name, Message_Type_value)
	proto.RegisterEnum("messages.Request_Type", Request_Type_name, Request_Type_value)
	proto.RegisterEnum("messages.Response_Type", Response_Type_name, Response_Type_value)
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xbf, 0x6e, 0xab, 0x30,
	0x18, 0xc5, 0xaf, 0x81, 0x1b, 0xe0, 0x4b, 0x84, 0xb8, 0xdf, 0x70, 0x8b, 0xaa, 0x0e, 0x29, 0x53,
	0xda, 0xa8, 0x0c, 0xe9, 0xd0, 0x39, 0x12, 0xa4, 0x62, 0x81, 0xc4, 0x90, 0xb9, 0xa2, 0xc1, 0xaa,
	0x3a, 0x14, 0x28, 0xa6, 0x43, 0xde, 0xaa, 0x8f, 0xd4, 0xbd, 0x2f, 0x51, 0xc5, 0x31, 0xe4, 0x4f,
	0x23, 0x65, 0xf3, 0xb1, 0x7f, 0xc6, 0xe7, 0x9c, 0x0f, 0xb0, 0xde, 0x18, 0xe7, 0xd9, 0x0b, 0xe3,
	0x5e, 0x55, 0x97, 0x4d, 0x89, 0x46, 0xab, 0xdd, 0x2f, 0x02, 0xba, 0x14, 0x78, 0x0b, 0x5a, 0xb3,
	0xae, 0x98, 0x43, 0x86, 0x64, 0x64, 0x4d, 0xfe, 0x7b, 0xdd, 0x25, 0xb9, 0xf0, 0xd2, 0x75, 0xc5,
	0xa8, 0x60, 0xf0, 0x06, 0x7a, 0x9c, 0x15, 0x39, 0xab, 0x1d, 0x65, 0x48, 0x46, 0xfd, 0xc9, 0xbf,
	0x1d, 0xbd, 0x2a, 0x8b, 0x26, 0x5b, 0x35, 0x54, 0x02, 0x38, 0x06, 0x9d, 0xb2, 0xf7, 0x0f, 0xc6,
	0x1b, 0x47, 0x3d, 0x66, 0xeb, 0xed, 0x01, 0x6d, 0x09, 0xf4, 0xc0, 0xa0, 0x8c, 0x57, 0x65, 0xc1,
	0x99, 0xa3, 0x09, 0x1a, 0xf7, 0xe9, 0xed, 0x09, 0xed, 0x18, 0xf7, 0x1a, 0xb4, 0x8d, 0x2b, 0xec,
	0x83, 0x4e, 0x83, 0xc5, 0x32, 0x48, 0x52, 0xfb, 0x0f, 0x0e, 0xc0, 0xa0, 0x41, 0x32, 0x8f, 0xa3,
	0x24, 0xb0, 0x89, 0xfb, 0x49, 0x40, 0x97, 0xef, 0xe0, 0x15, 0x98, 0xf2, 0x6b, 0xa1, 0x2f, 0x72,
	0xaa, 0x74, 0xb7, 0xd1, 0x15, 0xa0, 0x1c, 0x17, 0x20, 0xaf, 0xef, 0x17, 0x60, 0x81, 0x12, 0xfa,
	0x22, 0x90, 0x49, 0x95, 0xd0, 0x47, 0x04, 0x2d, 0xcf, 0x9a, 0x4c, 0x98, 0x1e, 0x50, 0xb1, 0x76,
	0x1f, 0xa4, 0x39, 0x03, 0xb4, 0x79, 0x18, 0x3d, 0x6e, 0x9d, 0xcd, 0xc2, 0xc8, 0x8f, 0x62, 0x3f,
	0xb0, 0x49, 0xab, 0xfc, 0x69, 0x3a, 0xb5, 0x15, 0x34, 0xe1, 0x6f, 0x92, 0xc6, 0x34, 0xb0, 0x55,
	0xf7, 0x9b, 0x80, 0xd1, 0x86, 0x3d, 0xe3, 0x79, 0x7c, 0xe0, 0xf9, 0xe2, 0x77, 0x59, 0xfb, 0xa6,
	0xef, 0xc0, 0x90, 0xd3, 0xe1, 0x8e, 0x3a, 0x54, 0x4f, 0xcf, 0xad, 0x43, 0x4e, 0x66, 0x5a, 0x9c,
	0xc9, 0x84, 0x60, 0xb5, 0x99, 0x9e, 0x66, 0xf1, 0x32, 0xf2, 0x6d, 0xe5, 0x60, 0x6f, 0x83, 0x25,
	0xb6, 0xba, 0x4b, 0xab, 0xb9, 0x31, 0xe8, 0xf2, 0x49, 0xd9, 0x2a, 0xe9, 0x5a, 0x75, 0x40, 0xcf,
	0xf2, 0xbc, 0x66, 0x9c, 0x8b, 0x80, 0x26, 0x6d, 0x25, 0x5e, 0x82, 0x91, 0xbf, 0xf2, 0x26, 0x2b,
	0x56, 0x4c, 0x4e, 0xa1, 0xd3, 0xcf, 0x3d, 0xf1, 0x97, 0xdf, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x31, 0xc1, 0x73, 0xc0, 0xf7, 0x02, 0x00, 0x00,
}
